import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sections/Sidebar";
import Header from "@/components/sections/Header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <main className="flex">
          <Sidebar />
          <div className="flex-1">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
